FROM python:3.6.5-slim

WORKDIR /app

COPY . /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends gcc \
    && apt-get install -y default-libmysqlclient-dev \
                          mysql-client \
                          redis-tools \
    && pip install --upgrade pip \
    && pip install -r project/requirements.txt


CMD flask run -h 0.0.0.0